# Generated by Django 4.1.6 on 2023-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_work_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('issued_from', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.FileField(upload_to='document')),
                ('date', models.DateField(blank=True, null=True)),
                ('grade', models.FloatField()),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
