# Generated by Django 4.1.6 on 2023-02-24 08:44

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_certificate_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='favourite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='work',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
